---

- name: reload sysctl
  shell: sysctl -p
  ignore_errors: true
  notify: restart lsyncd
  

- name: restart lsyncd
  service:
    name: lsyncd
    state: restarted
 
- name: restart csync2
  service:
    name: openbsd-inetd
    state: restarted
 
